# Generated by Django 4.1.2 on 2022-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_token',
            field=models.CharField(max_length=200),
        ),
    ]
