version: '3.9'

services:
  django:
    build: .
    image: django-docker:0.0.1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:5.7.22
    restart : always
    environment :
      - MYSQL_DATABASE='docic_db'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='root'
      - MYSQL_ROOT_PASSWORD='root'
    volumes:

      - .dbdata:/var/lib/mysql
    ports:
    - "3305:3306"

  